config/routes.rb
SummerApp::Application.routes.draw do

  root :to => "home#index"

  resources :home do
    collection do
      get :index
      post :send_sms
    end
  end

end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/sms_content.rb
class SmsContent < ActiveRecord::Base
  attr_accessible :content
end

app/models/summer_phone_number.rb
class SummerPhoneNumber < ActiveRecord::Base
  attr_accessible :phone_number
  validates :phone_number, format: { with: /[0-9]{10}/,
    message: "Phone Number should be valid." }
  # validates :phone_number, length: { is: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    flash[:notice] = ""
    flash[:error] = ""
    render :layout => 'application'
  end

  def send_sms
    summer_phone_number = SummerPhoneNumber.new(:phone_number => params[:phone_no])
    if summer_phone_number.save
      phone_number = "91#{params[:phone_no]}"
      content = SmsContent.first.content
      sms_sent_count = SummerPhoneNumber.where('phone_number = ? and trunc(created_at) = ?', params[:phone_no], Time.zone.today).count
      notice = ""
      if sms_sent_count < 3
        Exotel::Sms.send(:from => Settings.exotel_number, :to => phone_number, :body => content)
        flash[:notice] = "Thank you. You will receive an SMS with the link to download the app."
      else
        flash[:notice] = "We already sent you an SMS. Try Tomorrow!"
      end
      flash[:error] = ""
      render :action => "index", :notice=> flash[:notice]
    else
      flash[:notice] = ""
      flash[:error] = summer_phone_number.errors.messages[:phone_number]
      render :action => "index", :error => flash[:error]
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row main-page">
    <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
      <!-- <h1>
        Checkout our Summer App
      </h1> -->
      <%# binding.pry %>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
          <% if defined?(flush_flash) and flush_flash == true %>
            <% flash.clear %>
          <% end %>
        <% end %>

      <div class="landing-text row">
          Enter your Mobile Number
      </div>

      <div class="row">
          <div class="send-app-link row">
            <%= form_tag send_sms_home_index_path, :id => 'send_sms_form' do -%>
              <div class="col-md-8 col-sm-6 col-xs-12">
                  <%= text_field_tag 'phone_no', '', maxlength: 10, class: "invalid  num-elem phone-number" %>
              </div>
              <div class="col-md-4 col-sm-6 col-xs-6 ">
                  <%= submit_tag "Get App Link", class: "btn secondary submit-number", style: "text-align:center;" %>
              </div>

            <% end %>
          </div>
          <div class="row-fluid">
              <div class="col-sm-6">
                <a href="http://j.mp/justsumr" class="appstr"></a>
              </div>
              <div class="col-sm-6">
                <a href=" http://j.mp/iJustsumr" class="playstr"></a>
              </div>
          </div>

      </div>
    </div>
    <div class="col-lg-5 col-md-5 col-sm-6 hidden-xs">
      <img src="https://s3.amazonaws.com/prod.justbooksclc.com/summer_app/phone.png" class="img-responsive" alt="">
    </div>
  </div>

  <div class="row sub-heading">
    <h3 id="how">How it Works</h3>
    <p>
      <b>JustBooks Summer App</b> is specially designed to take care of your children's summer reading requirement.
    </p>
    <p>
      A well curated list of books await you with categorization as per age group. We've made sure your children get a unique collection to read, from the classics to the latest in the world of children's literature.
    </p>
    <div class=" row container img-responsive">
      <div class="col-lg-3 col-xs-12 col-sm-12"><img src="https://s3.amazonaws.com/prod.justbooksclc.com/summer_app/wishlist.png" class="how-images" alt="">

        <div class="how-image-text col-xs-12 col-sm-12">
          <h5> Add To Wishlist </h5>
          Browse through our specially curated set of books for the summer and add them to your personal wishlist
        </div>
      </div>
      <div class="col-lg-3 col-xs-12 col-sm-12"><img src="https://s3.amazonaws.com/prod.justbooksclc.com/summer_app/cart.png" class="how-images" alt="">
        <div class="how-image-text col-xs-12 col-sm-12">
          <h5> Rent your Book </h5>
          Place an order. Two Books from your wishlist will be selected and delivered at your doorstep
        </div>
      </div>
      <div class="col-lg-3 col-xs-12 col-sm-12"><img src="https://s3.amazonaws.com/prod.justbooksclc.com/summer_app/wallet.png" class="how-images" alt="">
        <div class="how-image-text col-xs-12 col-sm-12">
          <h5> Pay Once </h5>
          On your first delivery pay a one-time fee of Rs.1000 valid for 3 months of summer reading
        </div>
      </div>
      <div class="col-lg-3 col-xs-12 col-sm-12"><img src="https://s3.amazonaws.com/prod.justbooksclc.com/summer_app/repeat.png" class="how-images" alt="">
        <div class="how-image-text col-xs-12 col-sm-12">
          <h5> Repeat </h5>
          Request for the next set of books. Rent as many times at no additional cost
        </div>
      </div>
    </div>
    <p class="arial-italic">
      This service is currently available only across Mumbai.
    </p>
  </div>

  <div class="row sub-heading">
    <h3 id="about">About us</h3>
    <p>JustBooks clc is India’s largest community library chain with presence across India. The library has 65+ physical stores and operates on an online home delivery mechanism as well. For more information you may visit <a href="">www.justbooksclc.com.</a> </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Summer App</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!--BEGIN - Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-61728707-1', 'auto');
      ga('send', 'pageview');
    </script>
    <!-- END - Google Analytics -->

  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="https://s3.amazonaws.com/prod.justbooksclc.com/summer_app/logo-high-res.png", style="width:200px;"></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li><a href="#how">How It Works</a></li>
                <li><a href="#about">About</a></li>
            </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <div class="container footer">
      <div class="col-lg-4">
          Reach Out [ All the 7 days 9:30 AM to 6:00 PM ]
      </div>
      <div class="col-lg-4">
          Toll Free : 1-800-102-2665
      </div>
      <div class="col-lg-4">
          Customer Support customercare@justbooksclc.com
      </div>
  </div>
</body>
</html>